# Generated by Django 5.2.9 on 2026-01-02 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_content_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='internal_title',
            field=models.CharField(default='Blog', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(default=datetime.date(2026, 1, 2)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.DeleteModel(
            name='BlogContentBlock',
        ),
    ]
